create table tool (
    id BIGSERIAL NOT NULL PRIMARY KEY,
	tooltype VARCHAR(50) NOT NULL,
	steel BOOLEAN,
    stainless BOOLEAN,
    castiron BOOLEAN,
    aluminum BOOLEAN,
    universal BOOLEAN,
    catnum VARCHAR(50),
	invnum VARCHAR(50) NOT NULL,
    unit VARCHAR(10),
	grinded VARCHAR(10),
    mfr VARCHAR(50),
    holdertype VARCHAR(50),
    tipdiamm NUMERIC(10, 4),
    tipdiainch NUMERIC(10, 4),
    shankdia NUMERIC(10, 4),
    pitch VARCHAR(20),
    neckdia NUMERIC(10, 4),
    tslotdp NUMERIC(10, 4),
    toollen NUMERIC(10, 4),
    splen NUMERIC(10, 4),
    worklen NUMERIC(10, 4),
    bladecnt INT,
    tiptype VARCHAR(10),
    tipsize VARCHAR(10),
    material VARCHAR(20),
    coating VARCHAR(20),
    inserttype VARCHAR(50),
    cabinet VARCHAR(20),
    qty INT,
    issued INT,
    avail INT,
    minqty INT,
    ftscab VARCHAR(20),
    strcab VARCHAR(20),
    pfrcab VARCHAR(20),
    mitsucab VARCHAR(20),
    extcab INT,
    sourcetable VARCHAR(20),
    subtype VARCHAR(50) 
);

tipdia i pitch - vratit ce se na NUMERIC, zbog čahura (1-2, 3-4...) i navoja (4-40, 2-56...)

tooltype, steel, stainless, castiron, aluminum, universal, catnum, invnum, grinded, mfr, holdertype, tipdia, shankdia, pitch, neckdia, tslotdp, toollen, splen, worklen, bladecnt, tiptype, tipsize, material, coating, inserttype, cabinet, qty, issued, avail, minqty, ftscab, strcab, pfrcab, mitsucab, extcab