version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tooldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data