mapping_list = [
("fixture","Stezni prihvat(ER 11)", "Prihvat"),
("fixture","Visokoprecizne", "Čahura"),
("fixture","Visokoprecizne (GERC 16-HP)", "Čahura"),
("fixture","ER40 SPR-AA", "Čahura"),
("fixture","Prihvat (TENDO EC SET SK40 KD)", "Prihvat"),
("fixture","Čahura ER16", "Čahura"),
("fixture","Prihvat DIN 69871", "Prihvat"),
("fixture","Prihvat (TENDO EC SET HSK63 KD)", "Prihvat"),
("fixture","Stezna glava Chuck Mill", "Prihvat"),
("fixture","Visokoprecizne (GERC32-HP)", "Čahura"),
("fixture","Stezna glava", "Prihvat"),
("fixture","Visokoprecizne (GERC 16-B)", "Čahura"),
("fixture","Prihvat DIN 69871 AD", "Prihvat"),
("fixture","Nosač alata", "Prihvat"),
("fixture","ER20 SPR-AA", "Čahura"),
("fixture","Čahura ER32", "Čahura"),
("fixture","Prihvat DIN 69893", "Prihvat"),
("fixture","Prihvat DIN 69872", "Prihvat"),
("fixture","Prihvat DIN 6499", "Prihvat"),
("fixture","ER32 SPR-AA", "Čahura"),
("threadmaking","Glodalo za navoj", "Glodalo za navoj"),
("threadmaking","Glodalo za navoj(staro)", "Glodalo za navoj"),
("threadmaking","Uvaljivač za navoj", "Uvaljivač"),
("threadmaking","Glodalo za navoj(novo)", "Glodalo za navoj"),
("threadmaking","Ureznik", "Ureznik"),
("tool","Zabušivač", "Centar punta"),
("tool","T-glodalo(LASTIN REP)", "Lastin rep"),
("tool","Glodalo za grubu obradu čelika", "Glodalo"),
("tool","Mikroglodalo", "Glodalo"),
("tool","Profilno/specijalno glodalo", "Glodalo"),
("tool","Svrdlo(novo)", "Svrdlo"),
("tool","Glodaća glava 90°", "Glava"),
("tool","Rezna pločica", "Pločica"),
("tool","Trkač(BEZ VRHA)", "Trkač"),
("tool","Kruna za modularno svrdlo", "Pločica"),
("tool","Glodalo za grubu obradu(UNI)", "Glodalo"),
("tool","T-glodalo", "T-Glodalo"),
("tool","Glodalo za grubu obradu", "Glodalo"),
("tool","Mikro svrdlo(pilot)", "Svrdlo"),
("tool","Glodalo za upuštanje", "Upuštač"),
("tool","Obostrano radijusno glodalo", "Glodalo"),
("tool","Spiralni razvrtač", "Trivela"),
("tool","Kug. glodalo - MULTIMASTER", "Glodalo"),
("tool","Glodalo sa jednom oštricom", "Glodalo"),
("tool","Radijusno glodalo", "Glodalo"),
("tool","Radijusno-žensko glodalo", "Glodalo"),
("tool","Kuglasto glodalo(šroper)", "Glodalo"),
("tool","Kuglasto glodalo", "Glodalo"),
("tool","Mikroglodalo(kugla)", "Glodalo"),
("tool","Stepenasto svrdlo", "Svrdlo"),
("tool","Obost. glodalo za skidanje srha", "Trkač"),
("tool","Glodalo za skidanje srha(staro)", "Trkač"),
("tool","Zabušivač obostrani", "Centar punta"),
("tool","Vretenasto/konusno glodalo", "Glodalo"),
("tool","Vretenasto glodalo staro", "Glodalo"),
("tool","Profilno glodalo", "Glodalo"),
("tool","Čahura ER11(SET 1-7)", "Čahura"),
("tool","Glodalo sa dvije oštrice", "Glodalo"),
("tool","Mikro svrdlo", "Svrdlo"),
("tool","Torusno/Radijusno glodalo", "Glodalo"),
("tool","Kuglasto glodalo(lolipop)", "Glodalo"),
("tool","Alat za štosanje", "Alat za štosanje"),
("tool","Pila", "Pila"),
("tool","Trkač-(UPUŠTAČ)", "Upuštač"),
("tool","Glodalo za skidanje srha", "Trkač"),
("tool","Svrdlo sa izmjenjivom krunom", "Svrdlo"),
("tool","Glodaća glava 45°", "Glava"),
("tool","Profilno glodalo - DOVETAIL", "Lastin rep"),
("tool","Pločica za glodaču glavu", "Pločica"),
("tool","UNDERCUT", "Glodalo"),
("tool","Glodalo za lastin rep", "Lastin rep"),
("tool","Glodaća glava", "Glava"),
("tool","T-glodalo(ručno brušeno)", "T-Glodalo"),
("tool","Ravni razvrtač", "Trivela"),
("tool","Glodalo za skidanje srha(obos.)", "Trkač"),
("tool","Rezne pločice", "Pločica"),
("tool","Glodalo za skidanje srha(novo)", "Trkač"),
("tool","Glodalo za graviranje", "Glodalo"),
("tool","Vretenasto glodalo", "Glodalo"),
("tool","Svrdlo", "Svrdlo")
]